export * as otel from "npm:@opentelemetry/api@1.8.0";
export type { Attributes } from "npm:@opentelemetry/api@1.8.0";
export { OTLPTraceExporter } from "npm:@opentelemetry/exporter-trace-otlp-http@0.49.1";
export type { OTLPExporterNodeConfigBase } from "npm:@opentelemetry/otlp-exporter-base@0.49.1";
export { Resource } from "npm:@opentelemetry/resources@1.22.0";
export { BasicTracerProvider, BatchSpanProcessor } from "npm:@opentelemetry/sdk-trace-base@1.22.0";
export type { TracerConfig } from "npm:@opentelemetry/sdk-trace-base@1.22.0";
export * as conventions from "npm:@opentelemetry/semantic-conventions@1.22.0";
export type { Context, MiddlewareFn, RawApi, Transformer } from "npm:grammy@1";
export type { ApiMethods, Update } from "npm:grammy@1/types";
