name: Release

on:
  push:
    tags:
      - '*'

permissions:
  contents: write
  id-token: write

jobs:
  publish-jsr:
    name: Publish to JSR
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v1
      - run: deno publish

  publish-npm:
    name: Publish to npm
    needs: publish-jsr
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v1
      - uses: actions/setup-node@v3
        with:
          node-version: 20.x
          registry-url: https://registry.npmjs.org
      - name: Transform and Publish
        run: |
          deno task dnt ${{ github.ref_name }} ./mod.ts
          cd dist
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  create-release:
    name: Create Release
    needs: publish-npm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: softprops/action-gh-release@v1
        with:
          prerelease: true
          generate_release_notes: true
